const NAME = 'crisis-line';
const PLURAL_NAME = 'crisis-lines';
const CRISIS_LINES_LIST = 'CRISIS_LINES_LIST';

const CRISIS_LINE_MAX_DISTANCE = 100000; // * 100km

export {
  NAME, PLURAL_NAME,
  CRISIS_LINE_MAX_DISTANCE,
  CRISIS_LINES_LIST,
};
