const NAME = 'template';
const PLURAL_NAME = 'templates';

const SERVICE_CREATION_ADMIN = 'SERVICE_CREATION_ADMIN';
const SERVICE_UPDATION_ADMIN = 'SERVICE_UPDATION_ADMIN';
const SERVICE_DELETION_ADMIN = 'SERVICE_DELETION_ADMIN';
const AUTH_SIGNUP_ADMIN = 'AUTH_SIGNUP_ADMIN';
const APP_FEEDBACK_CREATION_ADMIN = 'APP_FEEDBACK_CREATION_ADMIN';
const SERVICE_FEEDBACK_CREATION_ADMIN = 'SERVICE_FEEDBACK_CREATION_ADMIN';
const SERVICE_APPROVAL_USER = 'SERVICE_APPROVAL_USER';
const SERVICE_FEEDBACK_CREATION_USER = 'SERVICE_FEEDBACK_CREATION_USER';
const SERVICE_INCREASE_KUDO_USER = 'SERVICE_INCREASE_KUDO_USER';

export {
  NAME, PLURAL_NAME,
  SERVICE_CREATION_ADMIN,
  SERVICE_UPDATION_ADMIN,
  SERVICE_DELETION_ADMIN,
  AUTH_SIGNUP_ADMIN,
  APP_FEEDBACK_CREATION_ADMIN,
  SERVICE_FEEDBACK_CREATION_ADMIN,
  SERVICE_APPROVAL_USER,
  SERVICE_FEEDBACK_CREATION_USER,
  SERVICE_INCREASE_KUDO_USER,
};
