const NAME = 'bot';

const CHATBOT_SOURCE = 'shelterapp';

const HOMELESS_RESOURCE_CATEGORY = 'HOMELESS_RESOURCE_CATEGORY';
const HOMELESS_RESOURCE_LOCATION = 'HOMELESS_RESOURCE_LOCATION';
const HOMELESS_RESOURCE_OPEN = 'HOMELESS_RESOURCE_OPEN';
const HOMELESS_RESOURCE_SERVICES = 'HOMELESS_RESOURCE_SERVICES';
const HOMELESS_RESOURCE_CITY_OR_ZIP = 'HOMELESS_RESOURCE_CITY_OR_ZIP';

const ASK_PARTICULAR_SERVICE = 'ASK_PARTICULAR_SERVICE';
const ASK_DISTANCE_SERVICE = 'ASK_DISTANCE_SERVICE'; // Ask Distance Service
const ASK_SERVICE_SCHEDULE = 'ASK_SERVICE_SCHEDULE';
const GET_SHELTER_AVAILABLE_BEDS = 'GET_SHELTER_AVAILABLE_BEDS'; // Get Shelter Available Beds
const ASK_SERVICE_BED_AVAILABLE = 'ASK_SERVICE_BED_AVAILABLE';
const CRISIS_LINES = 'CRISIS_LINES';
const WEATHER = 'WEATHER';

const SERVICE_MAX_DISTANCE = 100000; // * 100km

export {
  NAME,
  CHATBOT_SOURCE,
  HOMELESS_RESOURCE_CATEGORY,
  HOMELESS_RESOURCE_LOCATION,
  HOMELESS_RESOURCE_OPEN,
  HOMELESS_RESOURCE_SERVICES,
  HOMELESS_RESOURCE_CITY_OR_ZIP,
  CRISIS_LINES,
  WEATHER,
  ASK_PARTICULAR_SERVICE,
  ASK_DISTANCE_SERVICE,
  ASK_SERVICE_SCHEDULE,
  GET_SHELTER_AVAILABLE_BEDS,
  SERVICE_MAX_DISTANCE,
  ASK_SERVICE_BED_AVAILABLE,
};
