const HOMELESS_RESOURCE_CATEGORY = 'HOMELESS_RESOURCE_CATEGORY';
const HOMELESS_RESOURCE_LOCATION = 'HOMELESS_RESOURCE_LOCATION';
const HOMELESS_RESOURCE_OPEN = 'HOMELESS_RESOURCE_OPEN';

const HOMELESS_RESOURCE_SERVICES_REGEX = /open|near|close/;
const HOMELESS_RESOURCE_SERVICES_EVENT = 'homeless_resource_services_event';

export {
  HOMELESS_RESOURCE_CATEGORY,
  HOMELESS_RESOURCE_LOCATION,
  HOMELESS_RESOURCE_OPEN,
  HOMELESS_RESOURCE_SERVICES_REGEX,
  HOMELESS_RESOURCE_SERVICES_EVENT,
};

